# Copyright (C) 2008-today The SG++ project
# This file is part of the SG++ project. For conditions of distribution and
# use, please see the copyright notice provided with SG++ or at
# sgpp.sparsegrids.org

import ModuleHelper

Import("*")

moduleDependencies = ["sgppbase"]
additionalDependencies = []

module = ModuleHelper.Module(moduleDependencies, additionalDependencies)

module.scanSource()
module.buildLibrary()
module.generatePythonDocstrings()
module.buildExamples(recursive=True)
module.runExamples()
# Python examples live in a subfolder (runExamples does not recurse); run with RUN_PYTHON_EXAMPLES=1.
module.runExamples(exampleFolder="examples/python", language="python")
module.buildBoostTests()
module.runBoostTests()
module.checkStyle()
